# See https://redoc.ly/docs/cli/configuration/ for more information.
apiDefinitions:
  main: ./openapi.yaml
lint:
  extends:
    - recommended
  rules:
    # no changes here yet
referenceDocs:
  generateCodeSamples:
    languages: 
      - lang: curl
      - lang: JavaScript
      - lang: Java
      - lang: Node.js
      - lang: Python
  htmlTemplate: ./docs/index.html

  # Layout scope paginates the API for browser performance reasons.
  layout:
    scope: section
  routingStrategy: browser
  ctrlFHijack: true
  theme:
    colors:
      primary:
        main: "#0e1932"
